spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.232.133.137:3306/per_management
    username: yqydsb
    password: AsdLkj5201314
mybatis:
  mapper-locations: classpath:com/chinasofti/mapper/*.xml   #扫描静态资源文件夹下这个包下的所有后缀为xml的文件
  type-aliases-package: com.chinasofti.entity  #设置别名
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
server:
  servlet:
    jsp:
      init-parameters:
        development: true